# Generated by Django 5.1.7 on 2025-03-07 19:33

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("todo_app", "Category")
    Category.objects.create(name="Work", icon="icons/icon_1.png", owner=None)
    Category.objects.create(name="Personal", icon="icons/icon_1.png", owner=None)
    Category.objects.create(name="Shopping", icon="icons/icon_1.png", owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0005_category_task_category"),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
